theme: jekyll-theme-minimal
title: Pierre-Henri Delaval
description: Coaching, équipe, individuel - projets GitHub et outils métiers.
defaults:
  - scope:
      path: ""
    values:
      layout: default
